# Auto-generated by Sentinel Spec-to-Test Generator (baseline)
import pytest
from playwright.sync_api import sync_playwright, expect

TARGET_URL = "http://localhost:3001"

def test_resume_upload_and_ats_score():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.goto(TARGET_URL)

        # Verify file upload element exists
        file_input = page.locator("#resume-file")
        expect(file_input).to_be_visible()

        # Click analyze button
        analyze_btn = page.locator("#analyze-btn")
        expect(analyze_btn).to_be_visible()
        analyze_btn.click()

        # Verify results section & ATS score text
        results = page.locator("#results-section")
        expect(results).to_be_visible()

        score_element = page.locator("#ats-score")
        expect(score_element).to_have_text("Match Score: 85%")

        browser.close()

def test_export_pdf_report():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.goto(TARGET_URL)

        # Trigger analyze first to show results section
        analyze_btn = page.locator("#analyze-btn")
        analyze_btn.click()

        # Click export PDF button
        export_btn = page.locator("#export-pdf-btn")
        expect(export_btn).to_be_visible()
        export_btn.click()

        # Allow async API request to complete and verify no error is shown
        page.wait_for_timeout(500)
        error_display = page.locator("#error-display")
        expect(error_display).not_to_be_visible()

        browser.close()
