# Auto-generated by Sentinel Spec-to-Test Generator (baseline)
import pytest
from playwright.sync_api import sync_playwright, expect

TARGET_URL = "http://localhost:3001"

def test_refresh_leaderboard_and_rank_tier():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.set_default_timeout(3000)
        page.goto(TARGET_URL)

        # Click refresh leaderboard button
        refresh_btn = page.locator("#reload-leaderboard-btn")
        expect(refresh_btn).to_be_visible()
        refresh_btn.click()

        # Verify results section & rank badge tier text
        results = page.locator("#results-section")
        expect(results).to_be_visible()

        rank_badge = page.locator("#rank-badge")
        expect(rank_badge).to_have_text("Top Rank: Elite")

        browser.close()

def test_export_match_report():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.set_default_timeout(3000)
        page.goto(TARGET_URL)

        # Trigger refresh first to show results section
        refresh_btn = page.locator("#reload-leaderboard-btn")
        refresh_btn.click()

        # Click export match report button
        export_btn = page.locator("#export-btn")
        expect(export_btn).to_be_visible()
        export_btn.click()

        # Allow async API request to complete and verify no error is shown
        page.wait_for_timeout(500)
        error_display = page.locator("#error-display")
        expect(error_display).not_to_be_visible()

        browser.close()

if __name__ == "__main__":
    test_refresh_leaderboard_and_rank_tier()
    test_export_match_report()