import os
import sys
import re
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from openai import OpenAI
from src.config import SPECS_DIR, TESTS_DIR, GEMINI_API_KEY, GEMINI_BASE_URL, GEMINI_MODEL, TARGET_APP_URL, AI_PROVIDER

SYSTEM_PROMPT = """You are Sentinel's AI Test Generator.
Your task is to take a plain-English feature specification for a web application and generate a clean, robust Playwright Python test file using the standard Playwright sync API.

Requirements for generated test file:
1. Target URL must be http://localhost:3001 (or as specified).
2. Test file must contain standard test functions starting with `test_`.
3. Use exact element IDs with page.locator("#id") (e.g., page.locator("#resume-file"), page.locator("#analyze-btn")). DO NOT use page.get_by_id.
4. Include explicit error handling and assertion checks using expect(locator).to_be_visible() or expect(locator).to_have_text().
5. Return ONLY executable Python code — no markdown fences, no explanation text.
"""

BASELINE_PLAYWRIGHT_TEST = '''# Auto-generated by Sentinel Spec-to-Test Generator (baseline)
import pytest
from playwright.sync_api import sync_playwright, expect

TARGET_URL = "http://localhost:3001"

def test_refresh_leaderboard_and_rank_tier():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.set_default_timeout(3000)
        page.goto(TARGET_URL)

        # Click refresh leaderboard button
        refresh_btn = page.locator("#refresh-btn")
        expect(refresh_btn).to_be_visible()
        refresh_btn.click()

        # Verify results section & rank badge tier text
        results = page.locator("#results-section")
        expect(results).to_be_visible()

        rank_badge = page.locator("#rank-badge")
        expect(rank_badge).to_have_text("Top Rank: Elite")

        browser.close()

def test_export_match_report():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.set_default_timeout(3000)
        page.goto(TARGET_URL)

        # Trigger refresh first to show results section
        refresh_btn = page.locator("#refresh-btn")
        refresh_btn.click()

        # Click export match report button
        export_btn = page.locator("#export-btn")
        expect(export_btn).to_be_visible()
        export_btn.click()

        # Allow async API request to complete and verify no error is shown
        page.wait_for_timeout(500)
        error_display = page.locator("#error-display")
        expect(error_display).not_to_be_visible()

        browser.close()
'''

def generate_test_from_spec(spec_filename="leaderboard_spec.md"):
    spec_path = SPECS_DIR / spec_filename
    if not spec_path.exists():
        spec_path = SPECS_DIR / "resume_ats_spec.md"
        if not spec_path.exists():
            print(f"[Generator Error] Spec file not found at {spec_path}")
            return False

    with open(spec_path, "r", encoding="utf-8") as f:
        spec_content = f.read()

    output_path = TESTS_DIR / "test_leaderboard.py"

    if GEMINI_API_KEY:
        try:
            print(f"[Generator] Calling {AI_PROVIDER} API ({GEMINI_MODEL}) to generate Playwright test suite...")
            client = OpenAI(api_key=GEMINI_API_KEY, base_url=GEMINI_BASE_URL)
            response = client.chat.completions.create(
                model=GEMINI_MODEL,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": f"Generate Playwright Python test suite for this spec:\n\n{spec_content}"}
                ],
                temperature=0.2,
                timeout=15
            )
            code_out = response.choices[0].message.content.strip()
            # Extract clean Python block using regex if wrapped in markdown fences
            match = re.search(r"```python\s*(.*?)\s*```", code_out, re.DOTALL)
            if match:
                code_out = match.group(1).strip()
            else:
                match_generic = re.search(r"```\s*(.*?)\s*```", code_out, re.DOTALL)
                if match_generic:
                    code_out = match_generic.group(1).strip()
                else:
                    if code_out.startswith("```python"):
                        code_out = code_out[len("```python"):].strip()
                    elif code_out.startswith("```"):
                        code_out = code_out[3:].strip()
                    if code_out.endswith("```"):
                        code_out = code_out[:-3].strip()

            with open(output_path, "w", encoding="utf-8") as f:
                f.write(code_out)
            print(f"[Generator] Successfully generated test suite via {AI_PROVIDER} API at {output_path}")
            return True
        except Exception as e:
            print(f"[Generator Warning] {AI_PROVIDER} API call failed ({e}). Falling back to baseline spec generator...")

    # Fallback baseline template
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(BASELINE_PLAYWRIGHT_TEST.strip() + "\n")
    print(f"[Generator] Successfully generated Playwright test suite at {output_path} (baseline)")
    return True

if __name__ == "__main__":
    generate_test_from_spec()
